ReactiveX/RxCpp

- .gitignore
- Rx/v2/examples/cep/CMakeLists.txt
- Rx/v2/examples/cep/main.cpp
#105 
@lmouline 
`observable::create<T>()` takes one parameter. The parameter is a function. The easiest way to supply the function is to use a C++ lambda.
This sample shows how to use create to send keyboard events. C++ io will not consume 1 character at a time, so `cin::get()` does not return until space or return is pressed, then all the characters in the buffer are returned, one per call to `cin::get()`.
> add cep sample

- Rx/v2/src/rxcpp/operators/rx-subscribe_on.hpp
> fix #127 - subscribe_on lifetime broken

- Rx/v2/src/rxcpp/schedulers/rx-virtualtime.hpp
Thanks to @d-led for reporting this issue.  (https://github.com/d-led/ticker/commit/70dec6397e66bf8deb57cefc65fd751efb9453ff#commitcomment-11227516)
> fix bug reported in test scheduler

- Rx/v2/src/rxcpp/rx-coordination.hpp
- Rx/v2/src/rxcpp/schedulers/rx-test.hpp
add helpers for making coordinations.
> expose advance and sleep methods

- DeveloperManual.md
- README.md
I believe that it might help others joining this project later if some information about the code structure, etc. is described in an extra manual. So I started a new developer manual and added a slightly modified version of an answer that @kirkshoop posted on stackoverflow. I think this information is worth to be kept nearer to the code.
My plan is to add more information while I continue to read and understand the code.
Of course the document lacks some introductory chapter, but I tag this pull request as a minimum starting point.
What do you think?
> What do you think about a developer's manual?

- projects/CMake/CMakeLists.txt
Modified CmakeLists.txt such that the Visual Studio solution now has an
extra project "RxCpp" containing a virtual folder "src".
fixes #144
> Added RxCpp source files to solution

- Rx/v2/examples/doxygen/on_error_resume_next.cpp
- Rx/v2/examples/doxygen/tap.cpp
- Rx/v2/src/rxcpp/operators/rx-on_error_resume_next.hpp
- Rx/v2/src/rxcpp/operators/rx-tap.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-observer.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/on_error_resume_next.cpp
- Rx/v2/test/operators/tap.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
As requested in #158 - adds `on_error_resume_next()`
bonus - also adds `tap()`
> Tapandresume

- Ix/CPP/src/cpplinq/linq.hpp
- Ix/CPP/src/cpplinq/linq_cursor.hpp
- Ix/CPP/src/cpplinq/linq_iterators.hpp
- Ix/CPP/src/cpplinq/linq_select.hpp
- Ix/CPP/src/cpplinq/linq_skip.hpp
- Ix/CPP/src/cpplinq/linq_take.hpp
- Ix/CPP/unittest/testbench.cpp
- Ix/CPP/unittest/testbench.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
- Rx/v2/src/rxcpp/schedulers/rx-eventloop.hpp
- Rx/v2/src/rxcpp/schedulers/rx-test.hpp
- Rx/v2/src/rxcpp/sources/rx-range.hpp
- Rx/v2/src/rxcpp/subjects/rx-replaysubject.hpp
- Rx/v2/test/operators/zip.1.cpp
Issue: https://github.com/Reactive-Extensions/RxCpp/issues/164
> Fully qualify cstddef header types std::ptrdiff_t and std::size_t

- Rx/v2/src/rxcpp/rx-subscriber.hpp
Changing do_unsubscribe in nextedatcher to an atomic type resolves issue #175.
> Changed nextdetacher::do_unsubscribe memeber to an atomic type.

- Rx/v2/examples/doxygen/distinct.cpp
- Rx/v2/src/rxcpp/operators/rx-distinct.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/src/rxcpp/rx-predef.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/distinct.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
implemented using `std::unordered_set`.
`value` is used as a key.
> add distinct operator

- Rx/v2/examples/doxygen/sample.cpp
- Rx/v2/src/rxcpp/operators/rx-sample_time.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/sample.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
> add sample operator

- Rx/v2/examples/doxygen/delay.cpp
- Rx/v2/src/rxcpp/operators/rx-delay.hpp
- Rx/v2/src/rxcpp/operators/rx-finally.hpp
- Rx/v2/src/rxcpp/operators/rx-tap.hpp
- Rx/v2/src/rxcpp/rx-notification.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/delay.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
finally and tap work with operator| now
add delay operator
> Operator fixes

- README.md
- Rx/v2/examples/linesfrombytes/main.cpp
- Rx/v2/src/rxcpp/operators/rx-concat.hpp
- Rx/v2/src/rxcpp/operators/rx-concat_map.hpp
- Rx/v2/src/rxcpp/operators/rx-flat_map.hpp
- Rx/v2/src/rxcpp/operators/rx-group_by.hpp
- Rx/v2/src/rxcpp/operators/rx-merge.hpp
- Rx/v2/src/rxcpp/operators/rx-reduce.hpp
- Rx/v2/src/rxcpp/operators/rx-repeat.hpp
- Rx/v2/src/rxcpp/rx-grouped_observable.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
converts linesfrombytes example to use operator |
> make operator | work better

- Rx/v2/examples/doxygen/debounce.cpp
- Rx/v2/src/rxcpp/operators/rx-debounce.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/debounce.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [debounce](http://reactivex.io/documentation/operators/debounce.html) operator.
Thank you,
Grigoriy
> add debounce operator

- Rx/v2/examples/doxygen/contains.cpp
- Rx/v2/examples/doxygen/exists.cpp
- Rx/v2/src/rxcpp/operators/rx-any.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/contains.cpp
- Rx/v2/test/operators/exists.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [exists and contains](http://reactivex.io/documentation/operators/contains.html) operators.
Please review.
Thank you,
Grigoriy
> Added `exists` and `contains` operators

- Rx/v2/src/rxcpp/operators/rx-distinct.hpp
- Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp
- Rx/v2/src/rxcpp/operators/rx-sample_time.hpp
It looks I made a couple of errors there previously, sorry.
It should be fixed now, i tested it manually.
But there are no automated tests for free functions right now. Should we add them?
Thank you,
Grigoriy
> Updates for operator syntax

- Rx/v2/examples/doxygen/timeout.cpp
- Rx/v2/src/rxcpp/operators/rx-timeout.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/timeout.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added a variant of the [timeout](http://reactivex.io/documentation/operators/timeout.html) operator that accepts duration as a parameter.
Please review.
Thank you,
Grigoriy
> Added timeout operator

- Rx/v2/examples/doxygen/with_latest_from.cpp
- Rx/v2/src/rxcpp/operators/rx-with_latest_from.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/with_latest_from.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
> add with_latest_from

- Rx/v2/examples/doxygen/all.cpp
- Rx/v2/src/rxcpp/operators/rx-all.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/all.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [all](http://reactivex.io/documentation/operators/all.html) operator.
Thank you,
Grigoriy
> Added all operator

- Rx/v2/examples/doxygen/timestamp.cpp
- Rx/v2/src/rxcpp/operators/rx-timestamp.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/timestamp.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [timestamp](http://reactivex.io/documentation/operators/timestamp.html) operator.
Please, review
Thank you,
Grigoriy
> add timestamp operator

- Rx/v2/examples/doxygen/take_last.cpp
- Rx/v2/src/rxcpp/operators/rx-take_last.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/take_last.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [take_last](http://reactivex.io/documentation/operators/takelast.html) operator.
Please, review
Thank you,
Grigoriy
> add take_last operator

- Rx/v2/examples/doxygen/skip_last.cpp
- Rx/v2/src/rxcpp/operators/rx-skip_last.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/skip_last.cpp
- Rx/v2/test/operators/take_last.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [skip_last](http://reactivex.io/documentation/operators/skiplast.html) operator,
please review.
Thank you,
Grigoriy
> Added skip_last operator

- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-scheduler.hpp
remove some lambdas that were contributing to longer compile times.
> remove some lambdas

- Rx/v2/src/rxcpp/operators/rx-zip.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
- Rx/v2/test/operators/zip.cpp
- appveyor.yml
> fix zip completion

- Rx/v2/examples/doxygen/default_if_empty.cpp
- Rx/v2/examples/doxygen/switch_if_empty.cpp
- Rx/v2/src/rxcpp/operators/rx-switch_if_empty.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/default_if_empty.cpp
- Rx/v2/test/operators/switch_if_empty.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added [switch_if_empty, default_if_empty](http://reactivex.io/documentation/operators/defaultifempty.html) operators.
Thank you,
Grigoriy
> add switch_if_empty, default_if_empty

- Rx/v2/src/rxcpp/subjects/rx-subject.hpp
unsubscribe needs to create a new generation without the expired
subscription
addresses #242 reported by @diorcety
> fix lifetime issue in subject

- Rx/v2/src/rxcpp/rx-scheduler.hpp
fixes #245 
Thank you @VorpalBlade!
> initialize ordinal

- Rx/v2/src/rxcpp/rx-observable.hpp
- appveyor.yml
vs workarounds for #246 
Thanks @frankinshtein for the report!
> Vs2015u3fixes

- Rx/v2/src/rxcpp/operators/rx-group_by.hpp
- Rx/v2/test/operators/group_by.cpp
#249 explained that other rx impls have a different group_by behavior.
This turned out to be a very large change. the lifetime coordination
required some thread safety changes. I tried a version of this change
that introduced a coordination parameter, but the only shared state was
the count, so this change makes that int atomic, even when no threads
are involved. not ideal but I decided it was the best tradeoff.
> change group_by semantics

- Rx/v2/src/rxcpp/operators/rx-zip.hpp
- Rx/v2/src/rxcpp/rx-coordination.hpp
- Rx/v2/src/rxcpp/rx-predef.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
zip issues blocked doc publishing
> zip round eleventy-one

- projects/CMake/CMakeLists.txt
as requested in #255 
use
```
cmake -DCMAKE_INSTALL_PREFIX=<path> .
make install
```
> add support for `make install`

- .gitignore
- Rx/v2/src/rxcpp/rx-observable.hpp
reduces compile times and prepares for new operator patterns
> template observable member functions

- Rx/v2/src/rxcpp/operators/rx-debounce.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
- Rx/v2/test/operators/debounce.cpp
Reimplemented using the pattern for lifters.
Please review.
Thank you,
Grigoriy
> decouple debounce from observable

- Rx/v2/examples/linesfrombytes/main.cpp
- Rx/v2/src/rxcpp/operators/rx-observe_on.hpp
- Rx/v2/src/rxcpp/operators/rx-reduce.hpp
- Rx/v2/src/rxcpp/rx-coordination.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/src/rxcpp/rx-scheduler.hpp
- Rx/v2/src/rxcpp/rx-subscription.hpp
- Rx/v2/src/rxcpp/rx-test.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
- Rx/v2/src/rxcpp/schedulers/rx-currentthread.hpp
- Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp
- Rx/v2/src/rxcpp/schedulers/rx-runloop.hpp
- Rx/v2/src/rxcpp/schedulers/rx-test.hpp
- Rx/v2/src/rxcpp/schedulers/rx-virtualtime.hpp
- Rx/v2/src/rxcpp/subjects/rx-subject.hpp
- Rx/v2/src/rxcpp/subjects/rx-synchronize.hpp
- Rx/v2/test/operators/concat.cpp
- Rx/v2/test/operators/concat_map.cpp
- Rx/v2/test/operators/flat_map.cpp
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/merge.cpp
- Rx/v2/test/operators/reduce.cpp
- Rx/v2/test/operators/subscribe_on.cpp
breaking changes to accumulator and result selector function signature.
take and return by-value, reduce will move for you.
switch from abort to terminate
> decouple reduce

- Rx/v2/src/rxcpp/operators/rx-distinct.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/distinct.cpp
Decouple distinct from observable.
No implementation changes.
Please, review
Thank you,
Grigoriy
> decouple distinct from observable

- Rx/v2/src/rxcpp/operators/rx-debounce.hpp
- Rx/v2/src/rxcpp/operators/rx-delay.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/delay.cpp
Decoupled delay from observable.
Please, review
Thank you,
Grigoriy
> decouple delay from observable

- Rx/v2/src/rxcpp/operators/rx-element_at.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/element_at.cpp
Decoupled element_at from observable; no implementation changes.
Please review.
Thank you,
Grigoriy
> decouple element_at from observable

- Rx/v2/src/rxcpp/operators/rx-ignore_elements.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/ignore_elements.cpp
Decoupled ignore_elements from observable,
please review.
Thank you,
Grigoriy
> decouple ignore_elements from observable

- Rx/v2/src/rxcpp/operators/rx-all.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/all.cpp
Decoupled [all](http://reactivex.io/documentation/operators/all.html) from observable
Please review
Thank you,
Grigoriy
> decouple all from observable

- Rx/v2/src/rxcpp/operators/rx-any.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/contains.cpp
- Rx/v2/test/operators/exists.cpp
Decoupled [exists and contains](http://reactivex.io/documentation/operators/contains.html) from observable.
Please, review
Thank you,
Grigoriy
> decouple exists and contains from observable

- Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp
- Rx/v2/test/operators/buffer.cpp
- Rx/v2/test/operators/window.cpp
> fix window_with_time_or_count

- Rx/v2/src/rxcpp/operators/rx-finally.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/finally.cpp
Decoupled finally from observable, added tests.
Please review.
Thank you,
Grigoriy
> decouple finally from observable

- Rx/v2/src/rxcpp/operators/rx-map.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/concat_map.cpp
- Rx/v2/test/operators/flat_map.cpp
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/map.cpp
- Rx/v2/test/operators/scan.cpp
- Rx/v2/test/operators/subscribe_on.cpp
- Rx/v2/test/operators/take_until.cpp
- Rx/v2/test/operators/window.cpp
- Rx/v2/test/operators/window_toggle.cpp
- Rx/v2/test/subscriptions/subscription.cpp
Decopuled [map](http://reactivex.io/documentation/operators/map.html) from obervable, added tests.
Please, review
Thank you,
Grigoriy
> decouple map from observable

- Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/test/operators/distinct_until_changed.cpp
- Rx/v2/test/operators/take_while.cpp
This PR contains `take_while` operator implementation with tests. I'm not sure about coding standards and some of design decisions so I based the implementation mainly on `take` operator. Testes also are almost copy of `take` operator tests. Solves issue #283.
> Issue #283: take_while operator implementation

- Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp
- Rx/v2/test/operators/distinct_until_changed.cpp
Added a version of `distinct_until_changed` that takes a custom BinaryPredicate.
Please, review
Thank you,
Grigoriy
> distinct_until_changed - a version with BinaryPredicate

- Rx/v2/src/rxcpp/operators/rx-retry.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/retry.cpp
Decoupled `retry` from observable,
Thank you,
Grigoriy
> decouple retry from observable

- Rx/v2/examples/win_text/rx_windows_user.h
- Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/test/operators/distinct_until_changed.cpp
- Rx/v2/test/operators/take_while.cpp
Please check and review. This is major change to recently implemented `take_while` operator and I'm not sure if this is correct so any feedback is most welcome! And yes I remember about the snippet...
> decouple take_while from observable

- Rx/v2/examples/doxygen/any.cpp
- Rx/v2/examples/doxygen/is_empty.cpp
- Rx/v2/src/rxcpp/operators/rx-all.hpp
- Rx/v2/src/rxcpp/operators/rx-any.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/any.cpp
- Rx/v2/test/operators/is_empty.cpp
* Added [is_empty](http://reactivex.io/documentation/operators/contains.html) operator. Implemented in terms of `all`
* Exposed `any` operator. It was partially exposed before.
Thank you,
Grigoriy
> add is_empty operator

- Rx/v2/src/rxcpp/operators/rx-pairwise.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/pairwise.cpp
Just a minor update -- decoupled pairwise from observable..
Please review.
Thank you,
Grigoriy
> decouple pairwise from observable

- Rx/v2/src/rxcpp/operators/rx-amb.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/amb.cpp
- Rx/v2/test/operators/amb_variadic.cpp
Decoupled `amb` from observable, please review.
Thank you,
Grigoriy
> decouple amb from observable

- Rx/v2/src/rxcpp/operators/rx-timestamp.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/timestamp.cpp
Decoupled `timestamp` from observable, please review.
and Merry Christmas! :christmas_tree: 
Thank you,
Grigoriy
> decouple timestamp from observable

- Rx/v2/src/rxcpp/operators/rx-timeout.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/timeout.cpp
Decoupled `timeout` from observable, please review.
Thank you,
Grigoriy
> decouple timeout from observable

- Rx/v2/src/rxcpp/operators/rx-take.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/buffer.cpp
- Rx/v2/test/operators/concat_map.cpp
- Rx/v2/test/operators/flat_map.cpp
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/observe_on.cpp
- Rx/v2/test/operators/scan.cpp
- Rx/v2/test/operators/take.cpp
- Rx/v2/test/subscriptions/subscription.cpp
Decoupled `take` from `observable`, please review.
Thank you,
Grigoriy
> decouple take from observable

- Rx/v2/src/rxcpp/operators/rx-buffer_count.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/buffer.cpp
Decoupled `buffer` from observable, please review.
Thank  you,
Grigoriy
> decouple buffer from observable

- Rx/v2/src/rxcpp/operators/rx-buffer_time.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/buffer.cpp
Decoupled buffer_with_time from observable, please review.
Thank you,
Grigoriy
> decouple buffer_with_time from observable

- Rx/v2/src/rxcpp/operators/rx-buffer_time.hpp
- Rx/v2/src/rxcpp/operators/rx-buffer_time_count.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/buffer.cpp
Decouple `buffer_with_time_or_count` from observable,
please review.
Thank you,
Grigoriy
> decouple buffer_with_time_or_count from observable

- Rx/v2/src/rxcpp/operators/rx-window.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/window.cpp
Decouple `window` from observable,
please review.
Thank you,
Grigoriy
> decouple window from observable

- Rx/v2/src/rxcpp/operators/rx-window_time.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/window.cpp
Decoupled `window_with_time` from observable,
please review.
and a Happy New Year! :snowman_with_snow:
Thank you,
Grigoriy
> decouple window_with_time from observable

- Rx/v2/src/rxcpp/operators/rx-sample_time.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/sample.cpp
Decouple `sample_with_time` from observable, please review.
Thank you,
Grigoriy
> decouple sample_with_time from observable

- Rx/v2/src/rxcpp/operators/rx-merge.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/merge.cpp
- Rx/v2/test/operators/window.cpp
- Rx/v2/test/operators/window_toggle.cpp
Decoupled `merge` from observable, please review.
Thank you,
Grigoriy
> decouple merge from observable

- Rx/v2/src/rxcpp/operators/rx-take_last.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/take_last.cpp
Another minor update..
Decouple `take_last` from observable, please review.
Thank you,
Grigoriy
> decouple take_last from observable

- Rx/v2/src/rxcpp/operators/rx-take_until.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/take_until.cpp
Decoupled `take_until` from observable,
please review.
Thank you,
Grigoriy
> decouple take_until from observable

- Rx/v2/src/rxcpp/operators/rx-skip_last.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/skip_last.cpp
Decoupled `skip_last` from observable,
please review.
Thank you,
Grigoriy
> decouple skip_last from observable

- Rx/v2/src/rxcpp/operators/rx-reduce.hpp
- Rx/v2/src/rxcpp/operators/rx-scan.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/src/rxcpp/rx-predef.hpp
- Rx/v2/test/operators/scan.cpp
Decoupled `scan` from observable,
please review.
Thank you,
Grigoriy
> decouple scan from observable

- Rx/v2/src/rxcpp/subjects/rx-subject.hpp
Notice: `lock()`method of `std::weak_ptr` is [executed atomically](http://en.cppreference.com/w/cpp/memory/weak_ptr/lock)
> Patch for issue with lifetime of subject's observers #324

- Rx/v2/test/subjects/subject.cpp
some small changes to the perf test I made while validating #325 
@gchudnov, lets see if you can merge this once it passes :)
> print async during subject perf test

- Rx/v2/src/rxcpp/operators/rx-concat.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/buffer.cpp
- Rx/v2/test/operators/concat.cpp
- Rx/v2/test/operators/group_by.cpp
Decoupled `concat` from observable, please review.
Thank you,
Grigoriy
> decouple concat from observable

- Rx/v2/src/rxcpp/operators/rx-tap.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/tap.cpp
Decoupled `tap` from observable,
please review
Thank you,
Grigoriy
> decouple tap from observable

- Rx/v2/src/rxcpp/operators/rx-switch_if_empty.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/default_if_empty.cpp
- Rx/v2/test/operators/switch_if_empty.cpp
Decoupled `switch_if_empty`, `default_if_empty` from observable,
please review.
Thank you,
Grigoriy
> decouple switch_if_empty, default_if_empty from observable

- Rx/v2/src/rxcpp/operators/rx-switch_on_next.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/switch_on_next.cpp
Decoupled `switch_on_next` from observable, please review.
Thank you,
Grigoriy
> decouple switch_on_next from observable

- Rx/v2/src/rxcpp/operators/rx-concat_map.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/concat_map.cpp
Decoupled `concat_map` from observable, added some tests.
Please review.
Thank you,
Grigoriy
> decouple concat_map from observable

- Rx/v2/src/rxcpp/operators/rx-flat_map.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/flat_map.cpp
Decouple `flat_map` from observable, added some tests.
Please review.
Thank you,
Grigoriy
> decouple flat_map from observable

- Rx/v2/examples/linesfrombytes/main.cpp
- Rx/v2/src/rxcpp/operators/rx-start_with.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/start_with.cpp
Decoupled `start_with` from observable, added tests.
Please review...
Thank you,
Grigoriy
> decouple start_with from observable

- Rx/v2/src/rxcpp/operators/rx-subscribe_on.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/subscribe_on.cpp
Decoupled `subscribe_on` from observable,
please review.
Thank you,
Grigoriy
> decouple subscribe_on from observable

- Rx/v2/src/rxcpp/operators/rx-observe_on.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/operators/concat.cpp
- Rx/v2/test/operators/concat_map.cpp
- Rx/v2/test/operators/flat_map.cpp
- Rx/v2/test/operators/group_by.cpp
- Rx/v2/test/operators/merge.cpp
- Rx/v2/test/operators/observe_on.cpp
- Rx/v2/test/operators/subscribe_on.cpp
- Rx/v2/test/subscriptions/subscription.cpp
Decoupled `observe_on` from observable,
please review.
Thank you,
Grigoriy
> decouple observe_on from observable

- Rx/v2/src/rxcpp/schedulers/rx-runloop.hpp
See #154 for motivation for this PR...
Implementation decisions:
1. I've added a single callback as a `std::function<void()>`:
1. I don't think the task details are too relevant for the callback
2. I think there's only likely to be one callback needed to be registered at any one time, given the use case of integrating the Rx loop with external event loops.
2. The callback can be disconnected by setting it to `std::function<void()>{}`
> Add callback for when a task is added to a run-loop schedule

- Rx/v2/src/rxcpp/operators/rx-lift.hpp
- Rx/v2/src/rxcpp/operators/rx-subscribe.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
Updated docs for `lift` and `subscribe`
No other changes.
closes #343 
Please review.
Thank you,
Grigoriy
> doc update

- Rx/v2/src/rxcpp/operators/rx-buffer_time.hpp
- Rx/v2/src/rxcpp/operators/rx-subscribe.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/sources/rx-create.hpp
- Rx/v2/src/rxcpp/sources/rx-defer.hpp
- Rx/v2/src/rxcpp/sources/rx-empty.hpp
- Rx/v2/src/rxcpp/sources/rx-error.hpp
- Rx/v2/src/rxcpp/sources/rx-interval.hpp
- Rx/v2/src/rxcpp/sources/rx-iterate.hpp
- Rx/v2/src/rxcpp/sources/rx-never.hpp
- Rx/v2/src/rxcpp/sources/rx-range.hpp
- Rx/v2/src/rxcpp/sources/rx-scope.hpp
- Rx/v2/src/rxcpp/sources/rx-timer.hpp
- Rx/v2/test/operators/concat_map.cpp
- Rx/v2/test/operators/flat_map.cpp
- Rx/v2/test/operators/on_error_resume_next.cpp
- Rx/v2/test/operators/reduce.cpp
shift tests to include aliases
> move sources docs out of observable

- Rx/v2/test/subjects/subject.cpp
add test to verify behavior of has_observers() - prompted by #348
> test has_observers()

- Rx/v2/src/rxcpp/operators/rx-window_toggle.hpp
- Rx/v2/test/operators/window_toggle.cpp
encountered in #369
This one took some time to debug. 😬
> fix async lifetime in window_toggle

- Rx/v2/src/rxcpp/operators/rx-timeout.hpp
- Rx/v2/test/operators/timeout.cpp
Timeout triggers if no items are emitted.
Please review.
Thank you,
Grigoriy
> Fix timeout when no items are emitted

- Rx/v2/src/rxcpp/schedulers/rx-eventloop.hpp
- Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp
attempt to fix #393
use event_loop lifetime to unsubscribe from new_thread workers
tested with all the perf tests, but messing with thread lifetime can
break existing code.
> shutdown event loop threads

- Rx/v2/examples/doxygen/skip_while.cpp
- Rx/v2/src/rxcpp/operators/rx-skip_while.hpp
- Rx/v2/src/rxcpp/rx-includes.hpp
- Rx/v2/src/rxcpp/rx-observable.hpp
- Rx/v2/src/rxcpp/rx-operators.hpp
- Rx/v2/test/CMakeLists.txt
- Rx/v2/test/operators/skip_while.cpp
- projects/CMake/CMakeLists.txt
- projects/doxygen/CMakeLists.txt
Added skip_while operator (including tests, doxygen docu + samples)
> Add: Skip_while operator

- README.md
Keep up with the latest Visual Studio.
> Update ide build to Visual Studio 2017

- .travis.yml
- Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp
- Rx/v2/src/rxcpp/subjects/rx-replaysubject.hpp
attempted fixes for #412 and #465
> fixes for replay and moved-from container not being empty

- Rx/v2/src/rxcpp/operators/rx-merge_delay_error.hpp
> removing a pedantic compile warning

- Rx/v2/src/rxcpp/rx-scheduler.hpp
- Rx/v2/src/rxcpp/subjects/rx-synchronize.hpp
> Fix synchronize lock and recursion data race

- Rx/v2/src/rxcpp/subjects/rx-behavior.hpp
- Rx/v2/src/rxcpp/subjects/rx-replaysubject.hpp
> add this to captures due to c++20 deprecation

- Rx/v2/src/rxcpp/operators/rx-concat_map.hpp
- Rx/v2/src/rxcpp/operators/rx-flat_map.hpp
- Rx/v2/src/rxcpp/operators/rx-window_toggle.hpp
- Rx/v2/src/rxcpp/rx-util.hpp
> Mitigate the C2039 about retired `std::result_of`.
