ReactiveX/RxCpp

Rx/v2/src/rxcpp/operators/rx-buffer_time.hpp, Rx/v2/src/rxcpp/operators/rx-buffer_time_count.hpp, Rx/v2/src/rxcpp/operators/rx-window_time.hpp, Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp, Rx/v2/test/operators/buffer.cpp, Rx/v2/test/operators/window.cpp
The time operators use a scheduler and an input stream, these must be coordinated. 
scheduling all the signals using the same worker guarantees that they will not overlap. when using an immediate scheduler no serialization primitives are used.
NOTE: I want to revamp the scheduler to make virtual methods opt-in and remove all the action/subscribeable/recursion/coordination constructs.
=> schedule observer and subscription in buffer and window when using time

Ix/CPP/src/cpplinq/linq.hpp
The header `<cstddef>` should be included to declare a type `ptrdiff_t`.
Otherwise Ix won't compile with `g++ -std=c++1y`.
=> Including cstddef for ptrdiff_t

Rx/v2/src/rxcpp/operators/rx-observe_on.hpp, Rx/v2/src/rxcpp/rx-notification.hpp, Rx/v2/src/rxcpp/rx-scheduler.hpp, Rx/v2/src/rxcpp/rx-subscriber.hpp, Rx/v2/src/rxcpp/schedulers/rx-currentthread.hpp, Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp, Rx/v2/src/rxcpp/schedulers/rx-test.hpp, Rx/v2/src/rxcpp/schedulers/rx-virtualtime.hpp, Rx/v2/src/rxcpp/subjects/rx-synchronize.hpp, appveyor.yml
uses weak pointer to hold the worker in schedulable and empties queue
when new_thread worker and test worker lifetime ends.
=> fixes worker leaks (#101 & #132)

Rx/v2/src/rxcpp/operators/rx-observe_on.hpp, Rx/v2/src/rxcpp/operators/rx-repeat.hpp, Rx/v2/src/rxcpp/operators/rx-subscribe_on.hpp, Rx/v2/src/rxcpp/rx-scheduler.hpp, Rx/v2/src/rxcpp/schedulers/rx-runloop.hpp, Rx/v2/src/rxcpp/subjects/rx-subject.hpp, Rx/v2/test/operators/observe_on.cpp, Rx/v2/test/subjects/subject.cpp, Rx/v2/test/subscriptions/subscription.cpp, projects/CMake/CMakeLists.txt
I added the run loop scheduler to answer #151 
```cpp
#include "rxcpp/rx.hpp"
// create alias' to simplify code
// these are owned by the user so that
// conflicts can be managed by the user.
namespace rx=rxcpp;
int main()
{
std::cout << std::setw(16) << std::this_thread::get_id() << " <- main thread id" << std::endl;
using namespace std::chrono;
rx::schedulers::run_loop rl;
auto mainthread = rx::observe_on_run_loop(rl);
auto workthread = rx::synchronize_new_thread();
rx::composite_subscription lifetime;
rx::observable<>::interval(workthread.now() + milliseconds(100), milliseconds(400)).
map([](int i){
std::cout << std::setw(16) << std::this_thread::get_id() << ": " << i << std::endl;
return i;
}).
take_until(rx::observable<>::timer(seconds(1))).
subscribe_on(workthread). …
```
=> add run loop scheduler

Rx/v2/examples/linesfrombytes/CMakeLists.txt, Rx/v2/examples/linesfrombytes/main.cpp, projects/CMake/CMakeLists.txt
ported this [answer](http://stackoverflow.com/questions/31208418/split-iobservablebyte-to-characters-then-to-line/31213161#31213161) to rxcpp
also shows some of the recent work to make rxcpp work when the std namespace is ~~polluting~~ pulled-into the global namespace.
=> add lines from bytes example

Rx/v2/src/rxcpp/operators/rx-observe_on.hpp, Rx/v2/src/rxcpp/operators/rx-window.hpp, Rx/v2/src/rxcpp/operators/rx-window_time.hpp, Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp, Rx/v2/src/rxcpp/rx-observer.hpp, Rx/v2/src/rxcpp/rx-predef.hpp, Rx/v2/src/rxcpp/rx-subscriber.hpp, Rx/v2/src/rxcpp/subjects/rx-subject.hpp, Rx/v2/test/sources/create.cpp
removed dynamic_ and static_ 
Now using template specializations of observer instead.
I also added an observer specialization that stores a state and optionally takes 
Template Parameter | Function Type
-----|-----
OnNext | `void(State&, T)`
OnError | `void(State&, std::exception_ptr)`
OnCompleted | `void(State&)`
if a function is supplied it is called, if a function is not supplied then `State::on_next(T)`, `State::on_error(std::exception_ptr)`, `State::on_completed()` are called.
```cpp
rx::observable<>::create<int>(
[&](const rx::subscriber<int>& so){
// override the observer in the subscriber
auto sn = rx::make_subscriber<int>(so,
// override only on_next on the observer
rx::make_observer<int>(so.get_observer(),
[](rx::observer<int>& o, int v){
o.on_next(v + 1);
}));
sn.on_next(1); …
```
=> new observer

Rx/v2/src/rxcpp/schedulers/rx-eventloop.hpp
The constructors were creating one thread to few.
=> Fix event_loop creating N-1 threads

Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-util.hpp
fixes #184 
Now you don't have to define RXCPP_ON_IOS in order to use the library on Android.
=> improve support for android

Rx/v2/src/rxcpp/subjects/rx-subject.hpp
uses a weak_ptr to break a cycle that caused the leak that @benpope reported in #196
=> fix for leak

Rx/v2/test/operators/group_by.cpp, Rx/v2/test/subscriptions/subscription.cpp
Fixes a leak in a test and use make_shared instead of shared_ptr(new ...
=> Reduce use of new

Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-util.hpp, Rx/v2/test/operators/distinct.cpp
can be forced to use hash with the actual enum type
#define RXCPP_FORCE_HASH_ENUM 1
=> support hash of enum using underlying_type by default.

Rx/v2/src/rxcpp/rx-util.hpp, Rx/v2/test/operators/distinct.cpp
So here goes my try at it!
I wanted to make a is_primitive_type trait similar to is_string, but since both duration and time_point expose rep and period it resulted in partial template specialization ambiguous resolution. So I ended up with is_convertible.
=> add hash implementations for time_point and duration

Rx/v2/examples/doxygen/delay.cpp, Rx/v2/examples/doxygen/time_interval.cpp, Rx/v2/examples/doxygen/timestamp.cpp
duration:::count() return type varies, but printf spec does not..
=> fix issue with printf

Rx/v2/examples/doxygen/empty.cpp, Rx/v2/src/rxcpp/rx-sources.hpp, Rx/v2/src/rxcpp/sources/rx-empty.hpp, Rx/v2/test/CMakeLists.txt, Rx/v2/test/sources/empty.cpp
Exposed [empty](http://reactivex.io/documentation/operators/empty-never-throw.html) as a source.
Just for consistency with [never](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/src/rxcpp/sources/rx-never.hpp#L27) and [error](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/src/rxcpp/sources/rx-error.hpp#L90).
Thank you,
Grigoriy
=> Exposed empty as a source

Rx/v2/src/rxcpp/rx-coordination.hpp
returning local-static-object is not ok, for example:
```
auto coordA = serialize_same_worker(workerA);
...
auto coordB = serialize_same_worker(workerB);
```
coordB is actually same with workerA, not workerB.
=> fix issue with identity_same_worker, serialize_same_worker

Rx/v2/src/rxcpp/rx-observer.hpp
Allow to have a verbose abort, something like "terminate called after throwing an instance of " instead of nothing
=> Verbose abort

Rx/v2/examples/doxygen/sequence_equal.cpp, Rx/v2/src/rxcpp/operators/rx-sequence_equal.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/CMakeLists.txt, Rx/v2/test/operators/sequence_equal.cpp, projects/CMake/CMakeLists.txt, projects/doxygen/CMakeLists.txt
Added [sequence_equal](http://reactivex.io/documentation/operators/sequenceequal.html) operator.
In this commit, I used `!=` to check items for inequality.
Going to add a method with a binary predicate in one of the next commits.
Thank you,
Grigoriy
=> add sequence_equal operator

Rx/v2/src/rxcpp/operators/rx-sequence_equal.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-util.hpp
Introduced a helper function `equal_to` in rx-util.hpp that is used if no binary predicate is provided.
Added BinaryPredicate to sequence_equal.
Changed comparison to:
```
-                if (x != y) {
+                if (!state->pred(x, y)) {
```
Thank you,
Grigoriy
=> add BinaryPredicate to sequence_equal

Rx/v2/src/rxcpp/operators/rx-sequence_equal.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/test/operators/sequence_equal.cpp
Added Coordination to sequence_equal.
There are 4 versions of seqence_equal available:
```
auto sequence_equal(OtherSource&& t, BinaryPredicate&& pred, Coordination&& cn) const
auto sequence_equal(OtherSource&& t, BinaryPredicate&& pred) const
auto sequence_equal(OtherSource&& t, Coordination&& cn) const
auto sequence_equal(OtherSource&& t) const
```
I don't like the way `auto sequence_equal(OtherSource&& t, BinaryPredicate&& pred) const` is enabled, but `std::is_callable` is available only in C++17.
Please review.
Thank you,
Grigoriy
=> add Coordinator parameter to sequence_equal

Rx/v2/src/rxcpp/rx-notification.hpp
The alternative would be to configure Qt to not define emit. But obviously we are not able to do that in every project.
=> Removed naming conflict with Qt's emit define

Rx/v2/examples/doxygen/main.cpp, Rx/v2/examples/doxygen/range.cpp, Rx/v2/examples/doxygen/zip.cpp, Rx/v2/src/rxcpp/operators/rx-amb.hpp, Rx/v2/src/rxcpp/operators/rx-zip.hpp, Rx/v2/src/rxcpp/rx-connectable_observable.hpp, Rx/v2/src/rxcpp/rx-coordination.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-lite.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/src/rxcpp/rx-predef.hpp, Rx/v2/src/rxcpp/rx-util.hpp, Rx/v2/test/operators/zip.cpp, Rx/v2/test/test.h
made changes to the operator implementation pattern. using zip as the
first example.
- allows rx-lite.hpp to not include the operators and instead have the app explicitly include only the operators needed.
- allows all zip related logic to be only in the rx-zip.hpp. observable only has a forwarding function named zip and operators define zip_tag and its include_header member.
- improves docs by linking the observable and free operator methods to the single doc at file scope.
- operator_member_missing overloads allow static asserts to help usage.
- the include_header member of the zip_tag allows a static assert to ask for the zip file to be included when omitted in rx-lite mode
@gchudnov, as a regular operator contributor, I would especially appreciate your feedback here. Is this an …
=> decouple zip operator from observable

Rx/v2/src/rxcpp/operators/rx-filter.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/concat_map.cpp, Rx/v2/test/operators/filter.cpp, Rx/v2/test/operators/flat_map.cpp
Decoupled `filter` from `observable` without implementation changes.
btw,
It might be better to extract [these](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/test/operators/filter.cpp#L46-L66) conditional testing into separate tests without `#if`. In this way both cases will be verified. I can make a separate PR if you wish.
Thank you,
Grigoriy
=> Decouple filter from observable

Ix/CPP/src/cpplinq/linq.hpp, Ix/CPP/unittest/testbench.cpp
Implementation of the Interactive Sum:
1 - sum() can be called on element_type that is default-constructable and summable;
2 - sum(seed) can be called on element_type that is summable;
3 - sum(selector) can be used with a callable that returns a default-constructable and summable type;
4 - sum(selector, seed) can be used with a callable that returns any summable type;
=> Interactive Sum

Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/distinct_until_changed.cpp
Decoupled distinct_until_changed from observable
No implementation changes.
Please review.
Thank you,
Grigoriy
=> decouple distinct_until_changed from observable

Rx/v2/src/rxcpp/operators/rx-distinct_until_changed.hpp, Rx/v2/test/operators/distinct_until_changed.cpp
A fix for #284 
distinct_until_changed:
* Removed the invalid requirement for a type to be hashable.
* `operator==` is used to determine if two elements are equal.
* added test
=> fixes issue 284

Rx/v2/src/rxcpp/operators/rx-on_error_resume_next.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/on_error_resume_next.cpp
Decoupled `on_error_resume_next` from observable.
In a separate commit made `first_tag` to inherit from `reduce_tag`.
Thank you,
Grigoriy
=> decouple on_error_resume_next from observable

Rx/v2/src/rxcpp/operators/rx-sequence_equal.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/src/rxcpp/rx-util.hpp, Rx/v2/test/operators/sequence_equal.cpp
Decoupled `sequence_equal` from observable.
Please review.
FYI:
[Here](https://github.com/Reactive-Extensions/RxCpp/compare/master...gchudnov:sequence_equal-o2?expand=1#diff-5291158f99c1fafd323041704e108a21R792) I ported [std::negation](http://en.cppreference.com/w/cpp/types/negation) from C++17 and used it [for overload selection](https://github.com/Reactive-Extensions/RxCpp/compare/master...gchudnov:sequence_equal-o2?expand=1#diff-c3362080e2d5eeea4f8eee60638ba9ebR236). If that is not OK and should be done in a different way, let me know.
Thank you,
Grigoriy.
=> decouple sequence_equal from observable

Rx/v2/src/rxcpp/operators/rx-repeat.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/repeat.cpp
A minor update.. Decoupled `repeat` from `observable`.
Please review.
Thank you,
Grigoriy
=> decouple repeat from observable

Rx/v2/src/rxcpp/operators/rx-time_interval.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/time_interval.cpp
A minor update -- decoupled `time_interval` from observable.
Please review.
Thank you,
Grigoriy
=> decouple time_interval from observable

Rx/v2/src/rxcpp/operators/rx-skip.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/skip.cpp
Since `take` has been already decoupled, it is high time to do the same with `skip`.
=> decouple skip from observable

Rx/v2/src/rxcpp/rx-util.hpp
This fixes a bug with any_value_true
`rxcpp::util::any_value_true()(0, 2, 3, 0, 3)` will return 0
`rxcpp::util::any_value_true()(0, 2, 3, 0, 3)` will return 1
=> Fix a issue with rxcpp::util::any_value_true

Rx/v2/src/rxcpp/operators/rx-buffer_time_count.hpp, Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/window.cpp
Decoupled `window_with_time_or_count` from observable, fixed a couple of typos.
Please review.
Thank you,
Grigoriy
=> decouple window_with_time_or_count from observable

Rx/v2/src/rxcpp/operators/rx-skip_until.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/skip_until.cpp
Decoupled `skip_until` from observable.
To make it similar to `take_until`, added a version of skip_until with a time point.
Please review.
Thank you,
Grigoriy
=> decouple skip_until from observable

Rx/v2/src/rxcpp/schedulers/rx-test.hpp, Rx/v2/test/operators/skip_until.cpp, Rx/v2/test/operators/take_until.cpp
Exposed `to_time_point` on the test scheduler, updated `skip_until` and `take_until` tests,
please review.
Thank you,
Grigoriy
=> exposed to_time_point on the test scheduler

Rx/v2/src/rxcpp/operators/rx-window_toggle.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/window_toggle.cpp
Decoupled `window_toggle` from observable,
please review.
When decoupling, I removed traits and used `result_of` on ClosingSelector [here](https://github.com/Reactive-Extensions/RxCpp/compare/master...gchudnov:window_toggle-o2?expand=1#diff-7ab818a409f457349089e6f33a31e15bR60) are [here](https://github.com/Reactive-Extensions/RxCpp/compare/master...gchudnov:window_toggle-o2?expand=1#diff-7ab818a409f457349089e6f33a31e15bR302). If that's not ok, let me know.
Thank you,
Grigoriy
=> decouple window_toggle from observable

Rx/v2/src/rxcpp/operators/rx-ref_count.hpp, Rx/v2/src/rxcpp/rx-connectable_observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/operators/publish.cpp, Rx/v2/test/subscriptions/subscription.cpp
Decoupled `ref_count` from `connectable_observable`
Put the include to the bottom of `rx-operators.hpp` as there is a dependency in [rx-synchronize](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/src/rxcpp/subjects/rx-synchronize.hpp#L220)
Please review
Thank you,
Grigoriy
=> decouple ref_count from connectable_observable

Rx/v2/src/rxcpp/operators/rx-concat_map.hpp, Rx/v2/src/rxcpp/operators/rx-flat_map.hpp, Rx/v2/src/rxcpp/operators/rx-map.hpp, Rx/v2/src/rxcpp/operators/rx-on_error_resume_next.hpp, Rx/v2/src/rxcpp/operators/rx-reduce.hpp, Rx/v2/src/rxcpp/operators/rx-take_while.hpp, Rx/v2/src/rxcpp/operators/rx-window_time.hpp, Rx/v2/src/rxcpp/rx-observable.hpp
added aliases for some operators
transform (map)
merge_transform (flat_map)
concat_transform (concat_map)
switch_on_error (on_error_resume_next)
accumulate (reduce)
=> add aliases and fix docs

Rx/v2/src/rxcpp/operators/rx-repeat.hpp, Rx/v2/test/operators/repeat.cpp
This rewrite addresses two isssues.
1. Rx operator repeat with 0 time argument should return an empty sequence. The reasons for that:
* Rx API is designed based on traditional functional programming and the fact that Iterator/Observer patterns are functional duals. Repeat function with times argument in non-lazy languages with Iterator-implemented sequences returns empty sequence when called with 0 as times argument, it's natural for the Observer dual to behave simiraly
* Using 0 as "magic number" breaks algorithmic generality, i.e. passing a dynamic counter variable to repeat as argument leads to unexpected result
* Rx in other languages treat 0 that way (e.g. https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Observable.java#L8536 )
2. Get rid of dependency on dynamic state …
=> Rewrite repeat operator to handle 0 case correctly and not rely on magic numbers

Rx/v2/src/rxcpp/rx-observable.hpp
When building RxCPP with the latest VS2017 RC, the compiler emits error
C2672 on compiling a method.
There was some off-line discussion (Kirk Shoop was included) about the
legitimacy of the error. In either case, I'd anticipate that the error
could hit in VS2017RTW, so I'm offering this PR.
The change is very targeted -- a natural question is if this error could
arise in the methods around retry. For that and further discussion, I
have to point you to my colleagues participating in the off-line
discussion; for this particular patch all I could do was confirm the
latest RC still needs it to build.
=> Work-around for VS2017RC error C2672 building doc

Rx/v2/src/rxcpp/operators/rx-retry.hpp, Rx/v2/test/operators/retry.cpp
Fix 0 as magic number for infinite retry and decouple finite/infinite cases. 
This is similar to #356
=> Retry(0)/Retry() operator fix

Rx/v2/src/rxcpp/sources/rx-iterate.hpp
#355 reported that range-v3 ranges failed due to an errant `&` in the
`iterator_type`
=> fix iterator_type::value_type error

Rx/v2/src/rxcpp/operators/rx-repeat.hpp, Rx/v2/src/rxcpp/operators/rx-retry.hpp
Add subscription tracking to retry operator to mange lifetime.
Change method naming in repeat operator implementation to match generically with retry
=> Retry: subscription lifetime; repeat: generic naming

Rx/v2/src/rxcpp/operators/rx-repeat.hpp, Rx/v2/src/rxcpp/operators/rx-retry.hpp, Rx/v2/test/operators/retry.cpp
Change the parameter of retry to be counted one more time. 
The parameter 'times' in retry operator actually means the total number of tries, not the number of retries. This is some misunderstanding due to operator's naming and is explicitly documented in some Rx implementation descriptions:
* RxNet: http://www.introtorx.com/uat/content/v1.0.10621.0/11_FlowControl.html#Retry
* RxJS: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/retry.md
=> Retry operator argument semantics fix

appveyor.yml
Visual Studio 2017 is released and AppVeyor removed the RC image.
Made changes to the appveyor-config file to fix the [broken](https://ci.appveyor.com/project/kirkshoop/rxcpp-446/build/2.2.608) build
Please review.
Thank you,
Grigoriy
=> appveyor vs2017 image update

Rx/v2/src/rxcpp/schedulers/rx-test.hpp
I have no a rational explanation of my changes (may be optimizer does something wrong with a problem expression, I do not know), but now all tests passed with 32 bit release (with/without v140_xp):
`100% tests passed, 0 tests failed out of 65`
I found the minimal code which reproduces the problem with RelWithDebInfo build:
```
int main()
{
auto sc = rxsc::make_test();
std::vector<rxcpp::notifications::recorded<std::shared_ptr<rxcpp::notifications::detail::notification_base<int> > > > v;
auto xs = sc.make_hot_observable(v); // here is segmentation fault
return 0;
}
```
which failed in depth of std::make_shared:
```
return rxt::testable_observable<T>(
std::make_shared<hot_observable<T>>(state, create_worker(composite_subscription()), std::move(messages)));
``` 
After that I simplified the …
=> fixed https://github.com/Reactive-Extensions/RxCpp/issues/366

Rx/v2/src/rxcpp/subjects/rx-subject.hpp
I think this little code piece is harmless and meaningful.
Further explaining, there are two constructor of subject: 
```C++
subject()
: s(composite_subscription())
{
}
explicit subject(composite_subscription cs)
: s(cs)
{
}
```
to retrieve the auto-created subscription(in 1st constructor), we need a get_subscription() for subject.
=> Add get_subscription() for subject

Rx/v2/src/rxcpp/rx-observer.hpp
workaround for problem reported by @pedropalomo - https://github.com/kirkshoop/twitter/issues/5
=> disambiguate onerror from onnext

Rx/v2/src/rxcpp/rx-util.hpp
=> std::unexpected has been deprecated

Rx/v2/src/rxcpp/sources/rx-never.hpp
Browsing the project and found a typo. Changed "rx-naver.hpp" to "rx-never.hpp"
=> Typo in rx-never documentation

projects/CMake/CMakeLists.txt
When installing the headers (as far as I see there are no library files) into the system using `make install` installs them into `/usr/local/rxcpp/...` which is not a standard place for header files...  This PR fixes that by installing them into something more like `/usr/local/include/rxcpp/...`. Of course the `/usr/local` is just my default `CMAKE_INSTALL_PREFIX` which can be changed to whatever people like. This will allow me to package rxcpp more easily into and AUR package which I'll hopefully soon make because I didnt find any out there.
=> Add 'include' to the install path of the headers

Rx/v2/test/operators/group_by.cpp, Rx/v2/test/operators/pairwise.cpp, Rx/v2/test/subjects/subject.cpp
By default, RxCpp fails to build with clang-trunk due to `-Werror,-Wunused-lambda-capture` warnings. Remove unused lambda captures.
=> Fix clang-trunk -Wunused-lambda-capture warnings

Rx/v2/src/rxcpp/sources/rx-iterate.hpp
The following code does not compile with AppleClang 8.1.0.8020042 due to implementation of `std::array` internally storing array with one element even if it is declared as `std::array<T, 0>`.
```C++
class foo {
foo(int) {}
};
auto o = rxcpp::observable::empty<foo>();
```
This PR fixes this issue by using `std::initializer_list<T>` instead `of std::array<T, 0>`.
=> Fix rxcpp::observable<>::from<T>() when T is non-default constructable

Rx/v2/src/rxcpp/sources/rx-range.hpp
The following code does not compile since `std::abs` is not defined for unsigned types. Moreover, subtraction of two unsigned values may lead to unwanted behaviour.
```C++
auto a = 1u, b = 2u;
rxcpp::observable<>::range(a, b).subscribe([] {});
```
This PR fixes the issue with basic `std::max() - std::min()` approach, which is applicable for both signed and unsigned values.
=> Fix rxcpp::observable<>::range<T>() when T is unsigned type

Rx/v2/examples/doxygen/composite_exception.cpp, Rx/v2/examples/doxygen/merge_delay_error.cpp, Rx/v2/src/rxcpp/operators/rx-merge_delay_error.hpp, Rx/v2/src/rxcpp/rx-composite_exception.hpp, Rx/v2/src/rxcpp/rx-includes.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/test/CMakeLists.txt, Rx/v2/test/operators/merge_delay_error.cpp, projects/doxygen/CMakeLists.txt
The operator and its test is copy-pasted and modified accordingly from `merge`
It should behave the same way as JavaRx `mergeDelayError()` in the terms of semantics
=> Add rx-merge-delay-error operator

Rx/v2/examples/doxygen/buffer.cpp
Fix build error with Clang 6.0.0
```
/Users/andrei/CLionProjects/RxCpp/Rx/v2/examples/doxygen/buffer.cpp:174:14: error: lambda capture 'start' is not used [-Werror,-Wunused-lambda-capture]
[start](std::vector<long> v){
^
/Users/andrei/CLionProjects/RxCpp/Rx/v2/examples/doxygen/buffer.cpp:195:14: error: lambda capture 'start' is not used [-Werror,-Wunused-lambda-capture]
[start](std::vector<long> v){
```
=> Remove unused variable and captures in doxygen/buffer.cpp

Rx/v2/src/rxcpp/rx-scheduler.hpp
Because of disabled RVO, `exit_recursed_scope_type` destructor was called on return statement in `recursed_scope_type::reset`, making the call ineffective. This change allows to use it as intended when RVO is disabled.
=> Fix exit_recursed_scope_type dtor cleaning requestor early

Rx/v2/src/rxcpp/operators/rx-observe_on.hpp
The change allows to use different run loops during the program execution.
=> Remove static from observe_on_run_loop

Rx/v2/src/rxcpp/operators/rx-group_by.hpp, Rx/v2/src/rxcpp/rx-util.hpp
Miss static_assert line 80
Invalid static message line 394
=> group_by support DurationSelector

Rx/v2/test/operators/observe_on.cpp
notification uses SFINAE to compile for value_types that do not have operator==
lets see if vc has a problem with this test
=> adding test for nocompare observe_on

Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/test/operators/merge_delay_error.cpp
removes spinning from blocking submit. ran all perf tests on osx without issue.
should fix #430 and help with #451
=> fix blocking_observable::subscribe

Rx/v2/examples/doxygen/amb.cpp, Rx/v2/examples/doxygen/buffer.cpp, Rx/v2/examples/doxygen/combine_latest.cpp, Rx/v2/examples/doxygen/concat_map.cpp, Rx/v2/examples/doxygen/flat_map.cpp, Rx/v2/examples/doxygen/from.cpp, Rx/v2/examples/doxygen/group_by.cpp, Rx/v2/examples/doxygen/main.cpp, Rx/v2/examples/doxygen/main.hpp, Rx/v2/examples/doxygen/merge.cpp, Rx/v2/examples/doxygen/merge_delay_error.cpp, Rx/v2/examples/doxygen/observe_on.cpp, Rx/v2/examples/doxygen/pairwise.cpp, Rx/v2/examples/doxygen/range.cpp, Rx/v2/examples/doxygen/replay.cpp, Rx/v2/examples/doxygen/skip_until.cpp, Rx/v2/examples/doxygen/subscribe_on.cpp, Rx/v2/examples/doxygen/take_until.cpp, Rx/v2/examples/doxygen/with_latest_from.cpp, Rx/v2/examples/doxygen/zip.cpp
Building the docs (e.g. with `ninja doc`) failed with GCC (e.g. GCC 7.3
under Fedora 27) with some missing declaration errors.
Example:
../Rx/v2/examples/doxygen/main.cpp:7:13: error: no previous
declaration for ‘std::__cxx11::string get_pid()’
[-Werror=missing-declarations]
Thus, this change adds a shared declaration for `get_pid()` that is
included by all users/the file where it's defined such that
accidental deviation in the signature are immediately noticed (as
compile error).
Similarly, the visibility of the example `less()` is changed to static
as it's only locally used.
With those changes the doc target succeeds again.
=> Fix doc target missing declarations errors

.travis.yml, Rx/v2/examples/doxygen/composite_exception.cpp
This warning is reported by GCC 9.
The files hosted on SourceForge are not going to fade away.
=> Small fixes.

README.md
clang should be told to use libc++, otherwise it will
try to use libstdc++ which may be missing on some systems.
Resolves: #478
=> README: fix cmake generation snippet for clang/linux

projects/CMake/CMakeLists.txt
Remove 'RxCpp' library target when it's used outside of
Visual Studio. This was supposed to be a virtual target,
not an actual one that builds libRxCpp.so.
The build never worked because it was missing setting the
compiler/linker flags from shared.cmake
Resolves: #477
=> cmake: Fix 'make' generator targets

Rx/v2/src/rxcpp/rx-subscription.hpp
composite_subscription_inner had missing checks which could lead to add/remove/clear
racing against unsubscribe.
(See the issue for more details).
Fixes: #475
=> rxcpp: Fix data race in composite_subscription

Rx/v2/examples/doxygen/publish.cpp, Rx/v2/examples/doxygen/ref_count.cpp, Rx/v2/src/rxcpp/operators/rx-publish.hpp, Rx/v2/src/rxcpp/operators/rx-ref_count.hpp, Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/test/operators/publish.cpp, projects/doxygen/CMakeLists.txt
The existing `connectable_observable.ref_count()` operator calls
connect on the source when it's subscribed to.
Generalize this by allowing an optional parameter `other`, i.e.
`observable.ref_count(connectable_observable other)` to be used as the
connect target.
Useful for implementing diamond graphs while retaining composability:
```
A
/   \
B     C
\   /
D
|
E
auto A = ... | publish();
auto B = A | ...;
auto C = A | ...;
auto D = B | merge(C) | ref_count(A);
auto E = D | ...;
E | subscribe(...);
```
Resolves: https://github.com/ReactiveX/RxCpp/issues/484
=> operators: Add ref_count(other) operator overload.

Rx/v2/src/rxcpp/schedulers/rx-runloop.hpp
Thread sanitizer detects a data race in this run loop usage example https://github.com/ReactiveX/RxCpp/pull/154 
https://gist.github.com/lebdron/ee3e3e74250c27b2595a732bae5a9a22
Since queue can be accessed both by current thread and some other thread which calls `schedule()`, queue handles have to be protected by a lock.
=> Fix data race in run loop usage

Rx/v2/src/rxcpp/schedulers/rx-newthread.hpp
Greetings!
Some time ago I performed checks of some project which uses RxCpp with address sanitizer and got this:
```
==87760==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d000002810 at pc 0x000107a5ccd8 bp 0x70000f5b8dd0 sp 0x70000f5b8580
READ of size 8 at 0x60d000002810 thread T7
#0 0x107a5ccd7 in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x50cd7)
#1 0x105c0b181 in std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) chrono:859
#2 0x105c07d02 in …
```
=> Fix address sanitizer issue in new_worker (rx-newthread.hpp)

Rx/v2/src/rxcpp/operators/rx-ref_count.hpp
In VS2013.5, the following statement causes a compilation error. 
Notice that the same compatibility is done here.
https://github.com/ReactiveX/RxCpp/blob/f38fb8e3c30b01b07c57e08039b2942f1685224d/Rx/v2/src/rxcpp/rx-util.hpp#L67-L72
=> removed constexpr to support older VC compilers.

README.md, projects/CMake/CMakeLists.txt
Signed-off-by: exctues <alexnamecode@gmail.com>
The idea is to allow Config mode(not only Module) in find_package function.
So, now in order to import rxcpp in the other project what you need to do is:
1) install rxcpp by "make install"
2) add find_package(rxcpp CONFIG) into CMakeLists.txt
=> make find_package(rxcpp CONFIG) work through exporting TARGETS

README.md
Vcpkg is a C++ library manager that can install RxCpp using a single-line command, and can also provide support to integrate RxCpp in CMake projects easily.
=> Add instructions to install RxCpp using vcpkg

Rx/v2/src/rxcpp/rx-observable-fwd.hpp, Rx/v2/src/rxcpp/rx-operators.hpp, Rx/v2/src/rxcpp/rx-predef.hpp
Using https://github.com/aras-p/ClangBuildAnalyzer allowed us to check that including `rxcpp/rx.h` was taking significant part of build time. It was possible to reduce it by using `rx-lite`, but the forward declaring header allowed to reduce it even more, because `observable` is used in interfaces.
=> Observable forward declaration header

Rx/v2/src/rxcpp/rx-util.hpp
The template has several uses as values_from<int, sizeof...(ParamN)>::type(). This causes a cast issue as the second parameter by default is an int whereas we are passing a size_t.
=> Changed values_from template parameter to not cast.

Rx/v2/src/rxcpp/subjects/rx-behavior.hpp, Rx/v2/src/rxcpp/subjects/rx-replaysubject.hpp
In the case of using replay/behavioral subjects as local variables, it is possible to obtain a crash when the subject variable is destroyed, but the stream is still used.
=> [FixCrash][Perfomance]Remove unnecessary "this" capture for subjects to prevent crashes for stack subjects variables.

Rx/v2/src/rxcpp/rx-observable.hpp, Rx/v2/src/rxcpp/sources/rx-iterate.hpp, Rx/v2/test/CMakeLists.txt, Rx/v2/test/sources/create.cpp, Rx/v2/test/sources/defer.cpp, Rx/v2/test/sources/iterate.cpp
Reduce amount of copies in source operators. Especially for iterate/just/from: reduce from 12-15 copies + 5-6 moves per object + till 2-3 copies OR moves
=> [Perfomance] Significantly reduce amount of copies during source operators

README.md
@kirkshoop ,
I found a typo in linesfrombytes example in README.md file.
This example is not compiled in gcc and clang. But @victimsnino already fixed this problem in Rx/v2/examples/linesfrombytes!
=> Fix typo in linesfrombytes example

README.md
@kirkshoop ,
I followed instructions in the Readme document to build unit tests but I couldn't get them.
@ivan-cukic added disable building tests option in CMakeLists.txt. I think instructions for building unit tests in the Readme document was not updated with this changes.
=> Add missing CMake variables for building tests
